name: tomtomzim
favicon: null
layout_spectrum: 0.25036
typography_spectrum: 0.24746788619086146
title: discovering the grid...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
