title: discovering the grid...
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3924731
  brandStrength: 0.5
  lightness: 0.6164874
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  rhythmicContrast: 0.4605735
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: tomtomzim
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7007169
layout_spectrum: 0.05555556
